### ISSUE TITLE
Unable to start program, .NET-error

### ISSUE THREAD

**Issue by cy-one** [MacTee/KSP-Mod-Admin-aOS#74]
I do have .netFW installed (and your copy in the "NeededInstallations" just says "newer version installed") and I'm getting this:

Unexpected runtime error: "An attempt was made to load an assembly
from a network location which would have caused the assembly to be
sandboxed in previous versions of the .NET Framework. this release of
the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See
http://go.microsoft.com/fwlink/?LinkId=155569 for more information."

..."

Win7 64 bit, btw.

KSPMA.log
========
[07.05.2015 23:17:32.713] [1] Info    : ---> KSP MA v2.0.0.13 started <---
[07.05.2015 23:17:32.722] [1] Debug   : Loading languages ...
[07.05.2015 23:17:32.750] [1] Debug   : Loading languages done. (English, Fake language, Deutsch, Italiano, Русский)
[07.05.2015 23:17:33.418] [1] Info    : Loading KSPModAdmin settings ...
[07.05.2015 23:17:33.419] [1] Info    : No KSP Mod Admin settings found!
[07.05.2015 23:17:33.426] [1] Debug   : Loading plugins ...
[07.05.2015 23:17:33.438] [1] Error   : An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
Exception: System.NotSupportedException
Message: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
StackTrace:
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at KSPModAdmin.Core.Utils.PluginLoader.LoadPlugins[T_Interface](String path)
   at KSPModAdmin.Core.Controller.MainController.LoadPlugins()
[07.05.2015 23:17:45.633] [1] Error   : An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
Exception: System.NotSupportedException
Message: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
StackTrace:
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at KSPModAdmin.Core.Utils.PluginLoader.LoadPlugins[T_Interface](String path)
   at KSPModAdmin.Core.Controller.MainController.LoadSiteHandler()
   at KSPModAdmin.Core.Controller.MainController.Initialize()
   at KSPModAdmin.Core.Controller.MainController.ShowMainForm()
[07.05.2015 23:17:45.634] [1] Info    : ---> KSP MA v2.0.0.13 closed <---

**Comment by cy-one** [comment]
I had some issues with the "Known Issue"-solution (unblocking), couldn't reproduce. But program could start in the end, issue can be closed. Sorry for the inconvenience.

**Comment by MacTee** [comment]
Hi,

 

try this:

https://github.com/MacTee/KSP-Mod-Admin-aOS/wiki/Known-issues
